keys:
  # Users
  - &users:
    - &gburd 6423C518273734713931CB331C4814F03CA7C161
  # Hosts
  - &hosts:
    - &loki age1udt7tgf8pa0r278z6xwrzndg5w9jyvph8p0nycpqw3d39aal5u6skfv556

creation_rules:

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *loki
      pgp:
      - *gburd
