keys:
  # Users
  - &users:
    - &gburd D4BB42BE729AEFBD2EFEBF8822931AF7895E82DF
  # Hosts
  - &hosts:
    - &loki age1udt7tgf8pa0r278z6xwrzndg5w9jyvph8p0nycpqw3d39aal5u6skfv556

creation_rules:

  - path_regex: hosts/loki/secrets.ya?ml$
    key_groups:
    - age:
      - *loki
      pgp:
      - *gburd
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *loki
      pgp:
      - *gburd
