keys:
  # Users
  - &users:
    - &gburd D4BB42BE729AEFBD2EFEBF8822931AF7895E82DF
  # Hosts
  - &hosts:
    - &floki age1z2x0g05q2erpux006vwhul70d8akj9avrj67s9p27fm4ce32ly8qt8nllz

creation_rules:

  - path_regex: hosts/floki/secrets.ya?ml$
    key_groups:
    - age:
      - *floki
      pgp:
      - *gburd
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *floki
      pgp:
      - *gburd
