{ config, lib, pkgs, ... }:
# Make the Crates.io API token available to `cargo publish` WITHOUT putting it
# in the environment.
#
# It used to be exported as $CARGO_REGISTRY_TOKEN from fish conf.d and
# ~/.profile, which made it a global variable in every descendant process. That
# is a real exposure, not a theoretical one: with kernel.core_pattern=core.%p
# (workstations/common.nix) and `ulimit -c unlimited`, any crashing binary
# writes its whole address space, environment included, into a core file in its
# working directory. On this machine 49 such core files under ~/ws contained the
# live token, and core files land right next to source, one `git add -A` away
# from a public push.
#
# Cargo's own credential file is the fix. `cargo publish` reads the token from
# $CARGO_HOME/credentials.toml, so nothing needs to be exported. The file is
# written at activation from the sops secret (mode 600) rather than being baked
# into the world-readable Nix store.
#
# NB: this is defence in depth, not the only layer. The dump-guard pre-commit
# hook in cli/git.nix blocks core/vgcore/perf artifacts outright, and
# .gitignore lists them. Keeping the secret out of the environment removes the
# exposure at its source instead of relying on those catching it.
let
  tokenFile = config.sops.secrets."cargo/crates_io_token".path or null;
in
lib.mkIf (tokenFile != null) {
  # Written at activation, not via home.file: home.file would place the token
  # in the Nix store, which is world-readable.
  # Must run AFTER sops-nix, not merely after writeBoundary: sops-nix is what
  # decrypts tokenFile, and ordering only on writeBoundary let this step read a
  # STALE token (observed live after rotating the secret -- credentials.toml
  # kept the old value while the decrypted file already had the new one).
  home.activation.cargoCredentials =
    lib.hm.dag.entryAfter [ "writeBoundary" "sops-nix" ] ''
      if [ -r ${tokenFile} ]; then
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$HOME/.cargo"
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/install -m600 /dev/null \
          "$HOME/.cargo/credentials.toml"
        # Not $DRY_RUN_CMD: the redirect is what writes the content, and the
        # file was just created empty with the right mode above.
        {
          echo '# Generated by home-manager/_mixins/console/cargo.nix -- do not edit.'
          echo '[registry]'
          printf 'token = "%s"\n' "$(${pkgs.coreutils}/bin/cat ${tokenFile})"
        } > "$HOME/.cargo/credentials.toml"
      fi
    '';

  # Remove the old exports if a previous generation left them behind. fish
  # conf.d files are not cleaned up by home-manager when the entry disappears
  # from the config, so an unmanaged copy would keep exporting the token.
  home.activation.cargoTokenCleanup =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      stale="$HOME/.config/fish/conf.d/cargo-registry-token.fish"
      if [ -e "$stale" ] && [ ! -L "$stale" ]; then
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/rm -f "$stale"
      fi
    '';
}
