{ config, lib, ... }:
# Expose the Crates.io API token (sops secret "cargo/crates_io_token") as
# $CARGO_REGISTRY_TOKEN so `cargo publish` works non-interactively.
#
# The secret is decrypted to a file at activation time, so (like the Bedrock
# bearer token in ai/bedrock.nix) we read it at shell start rather than baking
# it into the Nix store. Guarded by `or null` so this module is a no-op on any
# host/platform that doesn't declare the secret.
let
  tokenFile = config.sops.secrets."cargo/crates_io_token".path or null;
in
lib.mkIf (tokenFile != null) {
  # fish: auto-sourced on every interactive/login session.
  home.file.".config/fish/conf.d/cargo-registry-token.fish".text = ''
    # Generated by home-manager/_mixins/console/cargo.nix — do not edit.
    if test -r ${tokenFile}
        set -gx CARGO_REGISTRY_TOKEN (cat ${tokenFile})
    end
  '';

  # bash/POSIX login shells (via ~/.profile).
  home.sessionVariablesExtra = ''
    # cargo.nix: export CARGO_REGISTRY_TOKEN for cargo publish.
    if [ -r ${tokenFile} ]; then
      export CARGO_REGISTRY_TOKEN="$(cat ${tokenFile})"
    fi
  '';
}
