# tea - official CLI for Gitea/Forgejo, used here against Codeberg.org.
#
# The login token is a Codeberg PAT held in sops under codeberg/tea_token
# (declared per host; floki's secrets.yaml also serves arnold, meh has its
# own). It used to be configured by hand, so a rotation meant editing
# ~/.config/tea/config.yml manually and the token lived only on disk.
#
# ~/.config/tea/config.yml cannot be a home.file symlink into the store:
# tea REWRITES it (it maintains `created`, and updates the login on
# `tea login edit`), and a store path is read-only. It would also put the
# token in the world-readable nix store. So render it at activation from the
# decrypted secret, mode 600, the same approach as console/cargo.nix.
#
# Ordering must include "sops-nix": with only writeBoundary this step can read
# a STALE token, which cargo.nix hit live after a rotation.
{ config, lib, pkgs, ... }:
let
  tokenFile = config.sops.secrets."codeberg/tea_token".path or null;
  cfg = "${config.xdg.configHome}/tea/config.yml";
in
{
  home.packages = with pkgs; [
    tea # Gitea/Forgejo CLI
  ];

  home.activation.teaConfig = lib.mkIf (tokenFile != null)
    (lib.hm.dag.entryAfter [ "writeBoundary" "sops-nix" ] ''
      if [ -r ${tokenFile} ]; then
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname ${cfg})"
        $DRY_RUN_CMD ${pkgs.coreutils}/bin/install -m600 /dev/null ${cfg}
        # Not $DRY_RUN_CMD: the redirect writes the content, and the file was
        # just created empty with the right mode above.
        #
        # Fields mirror what tea itself writes. `created` is tea's own
        # bookkeeping; 0 is accepted and tea refreshes it on next use.
        # ssh_key is the signing/auth key already managed by
        # modules/home-manager/ssh-management.
        {
          echo '# Generated by home-manager/_mixins/cli/tea.nix -- do not edit.'
          echo '# Token comes from sops (codeberg/tea_token); rotate it there.'
          echo 'logins:'
          echo '    - name: codeberg.org/gregburd'
          echo '      url: https://codeberg.org'
          printf '      token: %s\n' "$(${pkgs.coreutils}/bin/cat ${tokenFile})"
          echo '      default: true'
          echo '      ssh_host: codeberg.org'
          printf '      ssh_key: %s/.ssh/id_ed25519\n' "$HOME"
          echo '      insecure: false'
          echo '      ssh_certificate_principal: ""'
          echo '      ssh_agent: false'
          echo '      version_check: true'
          echo '      user: gregburd'
          echo '      created: 0'
          echo '      token_expiry: 0'
          echo 'preferences:'
          echo '    editor: false'
          echo '    flag_defaults:'
          echo '        remote: ""'
        } > ${cfg}
      fi
    '');
}
