{ config, lib, pkgs, ... }:
# agent-sandbox — run a coding agent (or any command) in an isolated
# environment, TRANSPARENT to the agent (no agent flags/cooperation, not
# vendor-specific). A rogue/confused agent can't touch things it shouldn't
# (SSH keys, sops secrets, ~/.aws, the Bedrock bearer token, other projects,
# the rest of $HOME); a runaway child is memory-capped and made the OOM
# killer's first victim so it dies in the sandbox (no cascade to terminals).
#
# Isolation is provided by firejail (namespace sandbox). firejail is enabled
# system-side by nixos/_mixins/services/firejail.nix; this module ships the
# per-user profiles + the launcher.
#
# Three tiers, pick with --tier (default: firejail):
#   firejail (default) — namespace sandbox via a shipped profile. Whitelists
#            cwd (rw); blacklists SSH keys, secrets, ~/.aws, bearer token.
#            --aws swaps in the agent-aws profile: same, plus a netfilter
#            egress firewall that allows only DNS + HTTPS (AWS APIs + the
#            gateway), denies the rest (controlled cloud access, no proxy).
#   docker   — container isolation (docker_29), host-net for the gateway.
#   microvm  — full QEMU microVM (documented, not yet auto-provisioned).
#
# Usage:
#   agent-sandbox claude               # firejail-isolated, no external net
#   agent-sandbox --aws codex          # + AWS-only egress firewall
#   agent-sandbox --mem 8G pi          # cap memory (rlimit) + OOM-first
#   agent-sandbox --tier docker claude
#   agent-sandbox -- bash              # isolated shell to inspect the sandbox
let
  cfg = config.programs.ai.sandbox;
  inherit (lib) mkEnableOption mkOption mkIf types;
  home = config.home.homeDirectory;

  commonProfile = ''
    # agent-sandbox base profile (generated by nix-config).
    # Drop privileges + shrink kernel attack surface.
    caps.drop all
    nonewprivs
    seccomp
    noroot

    # --- Hard-block sensitive paths (agent must never read these) ---
    blacklist ${home}/.ssh
    blacklist ${home}/.aws
    blacklist ${home}/.gnupg
    blacklist ${home}/.config/sops
    blacklist ${home}/.config/sops-nix
    blacklist ${home}/.config/claude-code/.bearer_token
    blacklist ${home}/.password-store
    blacklist ${home}/.netrc
    read-only ${home}/.gitconfig

    # Private /tmp + /dev so temp/devices don't leak across sandboxes.
    private-tmp
    private-dev
  '';

  agentProfile = pkgs.writeText "agent.profile" ''
    ${commonProfile}
    # Networking: share the host network namespace so the agent can reach
    # the LiteLLM gateway on 127.0.0.1:4000 (a fresh netns has its own
    # loopback and can't see the host gateway). Egress restriction is NOT
    # done here — the gateway is the single broker to AWS/Bedrock, so the
    # sandbox's job is filesystem isolation (SSH/secrets/AWS-creds blocked
    # above). Restrict outbound at the host firewall / gateway if needed.
    #
    # (firejail --netfilter is a no-op without a private --net, and a private
    # --net can't reach the host's loopback gateway — so per-sandbox egress
    # filtering is intentionally omitted for this loopback-broker design.)
    ignore net none
  '';

  # Kept for reference / future use: an AWS-scoped egress filter for the case
  # where a sandbox must reach AWS DIRECTLY (its own netns, not via the host
  # gateway). Not wired into a tier because the current design routes all
  # cloud access through the loopback LiteLLM gateway.
  awsNetfilter = pkgs.writeText "agent-aws.net" ''
    *filter
    :INPUT DROP [0:0]
    :FORWARD DROP [0:0]
    :OUTPUT DROP [0:0]
    -A INPUT -i lo -j ACCEPT
    -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    -A OUTPUT -o lo -j ACCEPT
    -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    -A OUTPUT -p udp --dport 53 -j ACCEPT
    -A OUTPUT -p tcp --dport 53 -j ACCEPT
    -A OUTPUT -p tcp --dport 443 -j ACCEPT
    COMMIT
  '';

  agentAwsProfile = pkgs.writeText "agent-aws.profile" ''
    ${commonProfile}
    # Own network namespace + filtered egress (DNS + HTTPS only) for a
    # sandbox that must reach AWS DIRECTLY rather than via the host gateway.
    # NOTE: in this netns the host's 127.0.0.1:4000 gateway is NOT reachable
    # (separate loopback); use this only for direct-AWS work where the agent
    # is given scoped creds via env. ~/.aws stays blacklisted.
    net ${cfg.awsNetDevice}
    netfilter ${awsNetfilter}
  '';

  agent-sandbox = pkgs.writeShellApplication {
    name = "agent-sandbox";
    # NOTE: firejail must be the SUID wrapper at /run/wrappers/bin/firejail
    # (installed by programs.firejail.enable), NOT the non-SUID nixpkgs store
    # binary — the store binary can't create /run/firejail's lockfile and
    # fails with 'preproc_lock_file: open: Permission denied'. So it is
    # deliberately absent from runtimeInputs and called by absolute path.
    runtimeInputs = [ pkgs.coreutils pkgs.docker_29 ];
    text = ''
      set -euo pipefail
      TIER=firejail
      MEM="${cfg.defaultMemMax}"
      AWS=0
      while [ $# -gt 0 ]; do
        case "$1" in
          --tier) TIER="$2"; shift 2 ;;
          --mem)  MEM="$2"; shift 2 ;;
          --aws)  AWS=1; shift ;;
          --)     shift; break ;;
          -*)     echo "agent-sandbox: unknown flag $1" >&2; exit 2 ;;
          *)      break ;;
        esac
      done
      [ $# -gt 0 ] || { echo "usage: agent-sandbox [--tier firejail|docker|microvm] [--aws] [--mem 8G] <cmd> [args...]" >&2; exit 2; }

      PROJECT="$PWD"

      # Human size (12G/512M/…) -> bytes for firejail --rlimit-as.
      mem_bytes() {
        local v n unit
        v=$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')
        n=$(printf '%s' "$v" | tr -dc '0-9')
        unit=$(printf '%s' "$v" | tr -dc 'GMK')
        case "$unit" in
          G) echo $(( n * 1024 * 1024 * 1024 )) ;;
          M) echo $(( n * 1024 * 1024 )) ;;
          K) echo $(( n * 1024 )) ;;
          *) echo "$n" ;;
        esac
      }

      case "$TIER" in
        firejail)
          if [ "$AWS" -eq 1 ]; then
            PROFILE="${home}/.config/firejail/agent-aws.profile"
          else
            PROFILE="${home}/.config/firejail/agent.profile"
          fi
          # firejail's OWN limits (do NOT wrap in systemd-run --scope: that
          # breaks firejail's SUID root ops -> 'create_empty_dir_as_root:
          # mkdir: Permission denied'):
          #   --rlimit-as caps virtual memory so a runaway can't exhaust RAM;
          #   --oom=900 raises the sandbox's OOM score so the kernel kills a
          #   runaway INSIDE the sandbox first, sparing terminals/session.
          exec /run/wrappers/bin/firejail --quiet --profile="$PROFILE" \
            --rlimit-as="$(mem_bytes "$MEM")" \
            --oom=900 \
            --private-cwd="$PROJECT" \
            --whitelist="$PROJECT" \
            "$@"
          ;;
        docker)
          exec docker run --rm -it \
            --network host \
            --memory "$MEM" \
            -v "$PROJECT":"$PROJECT":rw \
            -v "${home}/.config/litellm/keys":/keys:ro \
            -w "$PROJECT" \
            -e HOME="$PROJECT" \
            "${cfg.dockerImage}" "$@"
          ;;
        microvm)
          echo "agent-sandbox: microvm tier is documented but not auto-provisioned." >&2
          exit 3
          ;;
        *) echo "agent-sandbox: unknown tier '$TIER'" >&2; exit 2 ;;
      esac
    '';
  };
in
{
  options.programs.ai.sandbox = {
    enable = mkEnableOption "agent-sandbox: run agents isolated (firejail/docker/microvm)";
    defaultMemMax = mkOption {
      type = types.str;
      default = "12G";
      description = "Default memory cap for the sandbox (firejail --rlimit-as; a runaway is also OOM-first).";
    };
    dockerImage = mkOption {
      type = types.str;
      default = "nixos/nix:latest";
      description = "Base image for the docker tier.";
    };
    awsNetDevice = mkOption {
      type = types.str;
      default = "eth0";
      description = ''
        Network device firejail bridges into the --aws profile's private
        netns (for DIRECT AWS access, not via the host gateway). Set to the
        host's real uplink (e.g. enp0s… / wlan0). Only used by --aws.
      '';
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ agent-sandbox ];
    home.file = {
      ".config/firejail/agent.profile".source = agentProfile;
      ".config/firejail/agent-aws.profile".source = agentAwsProfile;
    };
  };
}
