{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.bedrock;
  inherit (lib) mkEnableOption mkOption types;
in
{
  options.programs.ai.bedrock = {
    enable = mkEnableOption "Amazon Bedrock configuration for AI agents";

    region = mkOption {
      type = types.str;
      default = "us-east-1";
      description = "AWS region for Bedrock API";
    };

    profile = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = "AWS profile to use for Bedrock authentication";
    };

    credentialsFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to AWS credentials file (managed by sops-nix)";
    };

    bearerTokenFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to AWS Bedrock bearer token file (managed by sops-nix)";
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      # Claude Code's per-tool config file. The env block in
      # ~/.claude/settings.json is patched at activation time below.
      home.file.".config/claude-code/config.json" = {
        text = builtins.toJSON {
          apiProvider = "bedrock";
          bedrockRegion = cfg.region;
          bedrockProfile = if cfg.profile != null then cfg.profile else "default";
        };
      };

      home.packages = with pkgs; [ awscli2 ];
    }

    (lib.mkIf (cfg.credentialsFile != null) {
      home.file.".aws/credentials".source = cfg.credentialsFile;
    })

    # Bearer-token-driven configuration. Two complementary outputs:
    #
    #   1. ~/.config/fish/conf.d/aws-bedrock-token.fish — auto-sourced by
    #      fish on every interactive/login session, regardless of whether
    #      home-manager's fish module is enabled. Reads the sops-decrypted
    #      bearer token at shell start and exports AWS_BEARER_TOKEN_BEDROCK
    #      so any tool launched from the shell (Kiro, Pi, Maki, terax-ai,
    #      AWS SDK, ...) can pick it up.
    #
    #   2. A home.activation script that patches ~/.claude/settings.json's
    #      env block in place. Claude Code reads its env from that file
    #      rather than the parent shell, so we keep this on for parity.
    (lib.mkIf (cfg.bearerTokenFile != null) {
      # Export only AWS_BEARER_TOKEN_BEDROCK at shell level. AWS_REGION and
      # AWS_PROFILE are intentionally left alone so non-Bedrock AWS workflows
      # (aws s3, named profiles, etc.) keep using whatever the user has
      # configured elsewhere; Bedrock with a bearer token does not need a
      # region in env (cross-region inference profile IDs carry it).
      home.file.".config/fish/conf.d/aws-bedrock-token.fish".text = ''
        # Generated by modules/home-manager/ai/bedrock.nix — do not edit.
        if test -r ${cfg.bearerTokenFile}
            set -gx AWS_BEARER_TOKEN_BEDROCK (cat ${cfg.bearerTokenFile})
        end
      '';

      home.activation.injectAwsBearerToken = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        SETTINGS_FILE="${config.home.homeDirectory}/.claude/settings.json"
        BEARER_TOKEN_FILE="${cfg.bearerTokenFile}"

        if [ -f "$SETTINGS_FILE" ] && [ -r "$BEARER_TOKEN_FILE" ]; then
          BEARER_TOKEN=$(cat "$BEARER_TOKEN_FILE")
          TMP_FILE=$(${pkgs.coreutils}/bin/mktemp)
          ${pkgs.jq}/bin/jq --arg token "$BEARER_TOKEN" \
            '.env.AWS_BEARER_TOKEN_BEDROCK = $token' \
            "$SETTINGS_FILE" > "$TMP_FILE"
          ${pkgs.coreutils}/bin/mv "$TMP_FILE" "$SETTINGS_FILE"
          echo "Updated AWS_BEARER_TOKEN_BEDROCK in $SETTINGS_FILE"
        elif [ ! -r "$BEARER_TOKEN_FILE" ]; then
          echo "Warning: Bearer token file not readable at $BEARER_TOKEN_FILE"
        fi
      '';
    })
  ]);
}
