{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.codex;
  inherit (lib) mkEnableOption mkOption types;

  litellmKey = "${config.home.homeDirectory}/.config/litellm/keys/codex.key";

  # Codex uses TOML; format is documented at
  #   https://github.com/openai/codex/blob/main/docs/config.md
  #
  # Codex 0.92 only knows two ways to authenticate to a custom provider:
  #   - `requires_openai_auth = true` (codex's built-in OpenAI login)
  #   - `env_key = "VAR_NAME"` (read API key from an env var at runtime)
  #
  # The 0.5x-era `auth.command` / `auth.args` keys are silently ignored
  # by 0.92 and the proxy returns 401 "No api key passed in." We use
  # env_key and have the launcher wrapper export the variable from the
  # per-host virtual-key file (no secrets in the config TOML, no secrets
  # baked into the Nix store).
  configToml = ''
    # Codex configuration — managed by home-manager. Routes through the
    # local LiteLLM proxy (modules/home-manager/ai/litellm.nix) instead
    # of talking to Bedrock directly. Auth: a per-host virtual key in
    # ~/.config/litellm/keys/codex.key, exported as $LITELLM_API_KEY by
    # the codex wrapper at launch.

    model = "${cfg.defaultModel}"
    model_provider = "${cfg.provider}"
    model_reasoning_effort = "${cfg.reasoningEffort}"
    approval_mode = "auto-edit"

    [model_providers.${cfg.provider}]
    name = "LiteLLM (local Bedrock proxy)"
    base_url = "${cfg.litellmUrl}"
    wire_api = "responses"
    env_key = "LITELLM_API_KEY"

    [mcp_servers.memelord]
    command = "${pkgs.memelord or pkgs.writeShellScript "memelord-stub" "exec npx -y memelord \"$@\""}/bin/memelord"
    args = ["serve"]
    enabled = true

    [mcp_servers.postgresq]
    url = "https://pg.ddx.io/mcp/"
    enabled = true

    [mcp_servers.context7]
    command = "npx"
    args = ["-y", "@upstash/context7-mcp@latest"]
    enabled = true

    [mcp_servers.memory]
    command = "npx"
    args = ["-y", "@modelcontextprotocol/server-memory"]
    enabled = true

    [mcp_servers.git]
    command = "${pkgs.uv}/bin/uvx"
    args = ["--from", "mcp-server-git", "mcp-server-git"]
    enabled = true

    [mcp_servers.sequential-thinking]
    command = "npx"
    args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    enabled = true
  '';
in
{
  options.programs.ai.codex = {
    enable = mkEnableOption "OpenAI Codex agent configuration";

    defaultModel = mkOption {
      type = types.str;
      # LiteLLM alias (see modules/home-manager/ai/litellm.nix). Resolves
      # to bedrock/converse/us.anthropic.claude-opus-4-8 with adaptive
      # thinking + output_config.effort=xhigh on the proxy side.
      default = "claude-opus-4-8";
      description = "Default LiteLLM model alias for codex.";
    };

    reasoningEffort = mkOption {
      type = types.enum [ "minimal" "low" "medium" "high" "xhigh" ];
      default = "high";
      description = ''
        Codex's model_reasoning_effort. The proxy side caps adaptive-
        thinking models (Opus 4.x) at xhigh via output_config.effort,
        so even with codex set to high, the model thinks at its
        configured ceiling on the LiteLLM side.
      '';
    };

    provider = mkOption {
      type = types.str;
      default = "local-litellm";
      description = ''
        model_providers.<id> name for codex's custom provider definition
        below. Built-in IDs (openai, ollama, lmstudio, amazon-bedrock)
        are reserved by codex and cannot be used here.
      '';
    };

    litellmUrl = mkOption {
      type = types.str;
      default = "http://127.0.0.1:4000/v1";
      description = "Base URL for the local LiteLLM proxy.";
    };
  };

  config = lib.mkIf cfg.enable {
    # codex CLI itself, plus a thin wrapper that reads the per-host
    # LiteLLM virtual key file at runtime and exports it as
    # LITELLM_API_KEY. The TOML's `env_key` directive then picks it up.
    home.packages = [
      (pkgs.writeShellScriptBin "codex" ''
        # Read the LiteLLM virtual key fresh on every invocation so a
        # rotated key file takes effect without re-login. Mode-600 file
        # generated by litellm.service's mint-keys ExecStartPost.
        if [ -r "${litellmKey}" ]; then
          export LITELLM_API_KEY="$(${pkgs.coreutils}/bin/cat "${litellmKey}")"
        else
          echo "codex: ${litellmKey} not readable; is litellm.service running?" >&2
          exit 78  # EX_CONFIG
        fi
        exec ${pkgs.codex}/bin/codex "$@"
      '')
    ];

    home.file = {
      ".codex/config.toml".text = configToml;
      # Instructions deployed by steering.nix
      # Skills deployed by skills.nix
    };
  };
}
