{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.hermes;
  inherit (lib) mkEnableOption mkOption types;

  # Hermes Agent is a fast-moving Python package (released 2026-05-29 as
  # v0.15.1; the upstream repo still ships frequent point releases). Rather
  # than pin every transitive into a Nix derivation we install it through
  # pipx during home-manager activation. This trades pure-Nix reproducibility
  # for keeping up with upstream automatically (`pipx upgrade` on every
  # switch). The pipx venv lives in ~/.local/share/pipx/venvs/hermes-agent
  # and the resulting `hermes` / `hermes-agent` shims land in ~/.local/bin
  # which the home-manager PATH appends after ~/.nix-profile/bin (so nix
  # always wins over local installs, see home-manager/default.nix).
  pipxBin = "${pkgs.pipx}/bin/pipx";
  # pipx will use whatever python3 is already on the user's PATH (3.13 from
  # the shared home.packages set). hermes-agent requires Python 3.11+, so
  # 3.13 satisfies; we deliberately don't pin a specific python here to
  # avoid buildEnv conflicts with the user's primary python3.
in
{
  options.programs.ai.hermes = {
    enable = mkEnableOption "Hermes Agent (NousResearch self-improving agent)";

    defaultModel = mkOption {
      type = types.str;
      # Bedrock has Opus 4.8 as of 2026-05-29 under the inference-profile ID
      # `us.anthropic.claude-opus-4-8` (no -v1:0 suffix in the new naming).
      #
      # IMPORTANT AUTH NOTE (verified 2026-05-29): hermes routes Claude
      # models through the bundled Anthropic SDK's AnthropicBedrock client
      # (anthropic 0.87.0), which upstream signs with SigV4 *only* — it would
      # otherwise FAIL with "could not resolve credentials from session" given
      # we carry only AWS_BEARER_TOKEN_BEDROCK (no IAM keys). We fix this with
      # an idempotent overlay patch (files/hermes/patch_bedrock_bearer.py),
      # applied to the pipx venv after every install/upgrade, that makes
      # get_auth_headers() emit an `Authorization: Bearer` header when the
      # bearer token is set (Bedrock's HTTPS endpoint accepts it directly) and
      # otherwise falls back to the unchanged upstream SigV4 path. The `hermes`
      # launcher wrapper below exports the token so the SDK sees it. Bump the
      # id when 4.9+ ships.
      default = "us.anthropic.claude-opus-4-8";
      description = "Default Bedrock model ID for Hermes (must be a real inference-profile ID).";
    };

    region = mkOption {
      type = types.str;
      default = "us-east-1";
      description = "AWS region for Bedrock invocations.";
    };

    extras = mkOption {
      type = types.listOf types.str;
      # `bedrock` pulls in boto3 for the Converse API. Add others (anthropic,
      # exa, firecrawl, fal) only if/when the user opts into them.
      default = [ "bedrock" ];
      description = "PyPI extras to install with hermes-agent (e.g. bedrock, anthropic, exa).";
    };

    autoUpgrade = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Run `pipx upgrade hermes-agent` on every home-manager activation.
        Disable to pin the venv to its current version (you can still bump
        manually with `pipx upgrade hermes-agent`).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      pkgs.pipx
      # `hermes` launcher wrapper. pipx installs the real binary at
      # ~/.local/bin/hermes; this nix-profile shim shadows it (nix-profile/bin
      # precedes ~/.local/bin on PATH) and exports AWS_BEARER_TOKEN_BEDROCK +
      # AWS_REGION so the SDK's (patched) Bedrock auth path can authenticate
      # regardless of the parent shell. Mirrors the pi/maki wrappers.
      (pkgs.writeShellScriptBin "hermes" ''
        if [ -r "$HOME/.config/claude-code/.bearer_token" ]; then
          export AWS_BEARER_TOKEN_BEDROCK="$(cat "$HOME/.config/claude-code/.bearer_token")"
          unset AWS_PROFILE AWS_DEFAULT_PROFILE \
                AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
                AWS_SDK_LOAD_CONFIG
        fi
        export AWS_REGION="''${AWS_REGION:-${cfg.region}}"
        exec "$HOME/.local/bin/hermes" "$@"
      '')
    ];

    # ~/.hermes/config.yaml — picked up by `hermes` on every invocation.
    # Mirrors the layout in the upstream Bedrock guide
    # (NousResearch/hermes-agent/website/docs/guides/aws-bedrock.md).
    home.file.".hermes/config.yaml".text = ''
      # Generated by modules/home-manager/ai/hermes.nix — do not edit.
      model:
        provider: bedrock
        default: ${cfg.defaultModel}
        reasoning_effort: high

      bedrock:
        region: ${cfg.region}
    '';

    home.activation.installHermesAgent = lib.hm.dag.entryAfter [ "writeBoundary" "linkGeneration" ] ''
      # Install (or upgrade) hermes-agent via pipx. pipx itself comes from
      # nix; the hermes-agent Python deps live in a private venv under
      # ~/.local/share/pipx/venvs/hermes-agent. The activation is idempotent.
      export PATH="${pkgs.pipx}/bin:${pkgs.coreutils}/bin:$HOME/.nix-profile/bin:/etc/profiles/per-user/$USER/bin:$PATH"
      export PIPX_HOME="$HOME/.local/share/pipx"
      export PIPX_BIN_DIR="$HOME/.local/bin"

      ${pkgs.coreutils}/bin/mkdir -p "$PIPX_BIN_DIR" "$PIPX_HOME"

      EXTRAS=${lib.escapeShellArg "[${lib.concatStringsSep "," cfg.extras}]"}
      SPEC="hermes-agent$EXTRAS"

      if ${pipxBin} list --short 2>/dev/null | ${pkgs.gnugrep}/bin/grep -q '^hermes-agent '; then
        ${if cfg.autoUpgrade then ''
          echo "[hermes] upgrading existing pipx venv..."
          ${pipxBin} upgrade --pip-args="--upgrade-strategy=only-if-needed" hermes-agent || \
            echo "[hermes] upgrade failed (will retry on next switch)"
        '' else ''
          echo "[hermes] already installed (auto-upgrade disabled)"
        ''}
      else
        echo "[hermes] installing $SPEC via pipx..."
        ${pipxBin} install --quiet "$SPEC" || {
          echo "[hermes] install failed — run 'pipx install $SPEC' manually" >&2
        }
      fi

      # Overlay patch: teach the bundled Anthropic SDK's Bedrock auth path to
      # accept AWS_BEARER_TOKEN_BEDROCK. Idempotent — safe to re-run after
      # every install/upgrade above. Any python3 works (the script only does
      # file IO); use the nix one for determinism.
      ${pkgs.python3}/bin/python3 ${./files/hermes/patch_bedrock_bearer.py} \
        "$PIPX_HOME/venvs/hermes-agent" || \
        echo "[hermes] bedrock bearer patch failed (non-fatal)"
    '';
  };
}
