{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.hermes;
  inherit (lib) mkEnableOption mkOption types;

  pipxBin = "${pkgs.pipx}/bin/pipx";
  litellmKey = "${config.home.homeDirectory}/.config/litellm/keys/hermes.key";
in
{
  options.programs.ai.hermes = {
    enable = mkEnableOption "Hermes Agent (NousResearch self-improving agent)";

    defaultModel = mkOption {
      type = types.str;
      # LiteLLM alias (modules/home-manager/ai/litellm.nix). The proxy
      # resolves it to bedrock/converse/us.anthropic.claude-opus-4-8 with
      # adaptive thinking + output_config.effort=xhigh server-side.
      default = "claude-opus-4-8";
      description = "Default LiteLLM-aliased model for Hermes.";
    };

    litellmUrl = mkOption {
      type = types.str;
      default = "http://127.0.0.1:4000/v1";
      description = "Base URL for the local LiteLLM proxy (OpenAI-compat endpoint).";
    };

    extras = mkOption {
      type = types.listOf types.str;
      # We no longer need the bedrock extra: traffic goes through the
      # LiteLLM proxy via the OpenAI-compatible endpoint, not the
      # Anthropic SDK's Bedrock adapter.
      default = [ ];
      description = "PyPI extras to install with hermes-agent (rarely needed under LiteLLM routing).";
    };

    autoUpgrade = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Run `pipx upgrade hermes-agent` on every home-manager activation.
        Disable to pin the venv to its current version (you can still bump
        manually with `pipx upgrade hermes-agent`).
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      pkgs.pipx
      # `hermes` launcher wrapper: reads the per-host LiteLLM virtual key
      # at every invocation and exports it as LITELLM_API_KEY (which the
      # config.yaml's `providers.litellm.key_env` references). All AWS /
      # Bedrock plumbing is unset defensively so the migration is a clean
      # break — hermes never sees AWS credentials.
      (pkgs.writeShellScriptBin "hermes" ''
        if [ -r "${litellmKey}" ]; then
          export LITELLM_API_KEY="$(${pkgs.coreutils}/bin/cat "${litellmKey}")"
        else
          echo "hermes: ${litellmKey} not readable; is litellm.service running?" >&2
          exit 78  # EX_CONFIG
        fi

        unset AWS_BEARER_TOKEN_BEDROCK AWS_REGION \
              AWS_PROFILE AWS_DEFAULT_PROFILE \
              AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
              AWS_SDK_LOAD_CONFIG \
              ANTHROPIC_API_KEY ANTHROPIC_BASE_URL \
              CLAUDE_CODE_USE_BEDROCK CLAUDE_CODE_SKIP_BEDROCK_AUTH \
              ANTHROPIC_BEDROCK_BASE_URL \
              LD_PRELOAD

        exec "$HOME/.local/bin/hermes" "$@"
      '')
    ];

    # ~/.hermes/config.yaml — picked up by `hermes` on every invocation.
    # Uses hermes' v12+ keyed `providers` schema (one entry per custom
    # provider). The top-level `model: "<provider>:<id>"` string form is
    # used so hermes routes through the named custom provider on every
    # invocation; the dict form (`model: {provider: ..., default: ...}`)
    # is honoured by the model picker but the `-z` oneshot path falls
    # back to auto-detection from the model name (which matches
    # "claude-*" against the built-in Anthropic provider).
    home.file.".hermes/config.yaml".text = ''
      # Generated by modules/home-manager/ai/hermes.nix — do not edit.
      # Routes through the local LiteLLM proxy
      # (modules/home-manager/ai/litellm.nix); auth via the per-host
      # virtual key in ~/.config/litellm/keys/hermes.key, exported as
      # LITELLM_API_KEY by the hermes launcher wrapper.
      #
      # The dict form of `model:` separates provider from default-model so
      # hermes' `resolve_inference_provider()` picks up `model.provider`
      # directly (without needing to colon-parse the model id, which only
      # accepts known-provider prefixes from `_KNOWN_PROVIDER_NAMES`).
      # "custom:<name>" selects the named entry in `providers.<name>` below.

      model:
        provider: "custom:litellm"
        default: ${cfg.defaultModel}
        reasoning_effort: high

      providers:
        litellm:
          # Keep `name` clean (no spaces / punctuation) so its normalised
          # form matches the `custom:litellm` selector in `model.provider`
          # above. `_normalize_custom_provider_name(name)` does
          # `name.strip().lower().replace(' ', '-')`, so a friendly name
          # with spaces would not match.
          name: "litellm"
          base_url: "${cfg.litellmUrl}"
          # `key_env` tells hermes to read the API key from the named
          # environment variable on every request, so a rotated keyfile
          # picks up on the next exec without restarting hermes.
          key_env: "LITELLM_API_KEY"
          default_model: ${cfg.defaultModel}
          api_mode: "chat"
    '';

    home.activation.installHermesAgent = lib.hm.dag.entryAfter [ "writeBoundary" "linkGeneration" ] ''
      # Install (or upgrade) hermes-agent via pipx. pipx itself comes from
      # nix; the hermes-agent Python deps live in a private venv under
      # ~/.local/share/pipx/venvs/hermes-agent. The activation is idempotent.
      export PATH="${pkgs.pipx}/bin:${pkgs.coreutils}/bin:$HOME/.nix-profile/bin:/etc/profiles/per-user/$USER/bin:$PATH"
      export PIPX_HOME="$HOME/.local/share/pipx"
      export PIPX_BIN_DIR="$HOME/.local/bin"

      ${pkgs.coreutils}/bin/mkdir -p "$PIPX_BIN_DIR" "$PIPX_HOME"

      EXTRAS=${lib.escapeShellArg (
        if cfg.extras == []
        then ""
        else "[${lib.concatStringsSep "," cfg.extras}]"
      )}
      SPEC="hermes-agent$EXTRAS"

      if ${pipxBin} list --short 2>/dev/null | ${pkgs.gnugrep}/bin/grep -q '^hermes-agent '; then
        ${if cfg.autoUpgrade then ''
          echo "[hermes] upgrading existing pipx venv..."
          ${pipxBin} upgrade --pip-args="--upgrade-strategy=only-if-needed" hermes-agent || \
            echo "[hermes] upgrade failed (will retry on next switch)"
        '' else ''
          echo "[hermes] already installed (auto-upgrade disabled)"
        ''}
      else
        echo "[hermes] installing $SPEC via pipx..."
        ${pipxBin} install --quiet "$SPEC" || {
          echo "[hermes] install failed — run 'pipx install $SPEC' manually" >&2
        }
      fi

      # NOTE: the bedrock-bearer-overlay patcher
      # (files/hermes/patch_bedrock_bearer.py) was removed when hermes
      # migrated to LiteLLM. The Anthropic SDK's bedrock auth path is no
      # longer reached because traffic goes through the OpenAI-compat
      # endpoint of the local proxy.
    '';
  };
}
