{ config, lib, ... }:
let
  cfg = config.programs.ai.lmstudio;
  inherit (lib) mkEnableOption mkOption types;
in
{
  options.programs.ai.lmstudio = {
    enable = mkEnableOption "LMStudio local model integration (NPU-accelerated)";

    apiBase = mkOption {
      type = types.str;
      default = "http://localhost:1234/v1";
      description = "LMStudio OpenAI-compatible API endpoint";
    };

    embeddingModel = mkOption {
      type = types.str;
      default = "text-embedding-nomic-embed-text-v1.5";
      description = "Default embedding model loaded in LMStudio";
    };
  };

  config = lib.mkIf cfg.enable {
    # Export LMStudio API base for tools that support OpenAI-compatible endpoints
    home.sessionVariables = {
      LMSTUDIO_API_BASE = cfg.apiBase;
      # Memelord can use this for embeddings instead of cold-starting HuggingFace
      MEMELORD_EMBEDDING_URL = "${cfg.apiBase}/embeddings";
      MEMELORD_EMBEDDING_MODEL = cfg.embeddingModel;
    };

    # Fish shell: export for interactive sessions
    home.file.".config/fish/conf.d/lmstudio.fish".text = ''
      # Generated by modules/home-manager/ai/lmstudio.nix — do not edit.
      set -gx LMSTUDIO_API_BASE "${cfg.apiBase}"
      set -gx MEMELORD_EMBEDDING_URL "${cfg.apiBase}/embeddings"
      set -gx MEMELORD_EMBEDDING_MODEL "${cfg.embeddingModel}"
    '';
  };
}
