{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.steering;
  inherit (lib) mkEnableOption mkOption types;

  steeringFiles = {
    "must-rules.md" = ./files/steering/must-rules.md;
    "coding-standards.md" = ./files/steering/coding-standards.md;
    "rust-conventions.md" = ./files/steering/rust-conventions.md;
    "workflow.md" = ./files/steering/workflow.md;
    "tools.md" = ./files/steering/tools.md;
    "aws-builder.md" = ./files/steering/aws-builder.md;
    "mcp-config.md" = ./files/steering/mcp-config.md;
    "postgresql-workflow.md" = ./files/steering/postgresql-workflow.md;
    "voice.md" = ./files/steering/voice.md;
  };

  # Per-project context scoping. The GLOBAL Claude CLAUDE.md should only
  # @import the UNIVERSAL rules (always relevant); DOMAIN files (e.g. the
  # 15k-char postgresql-workflow) are opt-in per project so they don't burn
  # context in unrelated repos (e.g. an OS-kernel project pulling in
  # Postgres steering). Domain files are still deployed to
  # ~/.claude/steering/ so a project CLAUDE.md can @import them on demand;
  # the `project-steering` helper (for .envrc) writes that project file.
  universalSteering = [
    "must-rules.md"
    "coding-standards.md"
    "workflow.md"
    "tools.md"
    "voice.md"
    "mcp-config.md"
  ];
  domainSteering = {
    postgresql = [ "postgresql-workflow.md" ];
    aws = [ "aws-builder.md" ];
    rust = [ "rust-conventions.md" ];
  };

  # Concatenated steering for agents that use a single instructions file
  allSteeringContent = builtins.concatStringsSep "\n\n"
    (map builtins.readFile (builtins.attrValues steeringFiles));

  # direnv helper: in a project's .envrc, run e.g.
  #   use project_steering postgresql aws      (or: eval "$(project-steering postgresql)")
  # to layer the chosen domain steering ON TOP of the global universal set,
  # for EVERY agent — each reads project context from a different place:
  #   - Claude + Pi  -> ./.claude/CLAUDE.md  @imports ./.claude/steering-domains.md
  #   - Codex + Maki + Pi -> ./AGENTS.md     references ./.agent-steering-domains.md
  #   - Kiro         -> ./.kiro/steering/<domain-file> (symlinks)
  # With no args it lists domains.
  #
  # NON-DESTRUCTIVE: never clobbers a hand-written CLAUDE.md/AGENTS.md — only
  # appends a single include line if absent (idempotent). The two generated
  # *-domains.md files + the .kiro/steering symlinks are local + host-path-
  # specific, so they're gitignored (see cli/git.nix).
  #
  # AGENTS.md is usually committed/shared, so the include there points at a
  # RELATIVE local file (.agent-steering-domains.md), not an absolute
  # ~/.claude/steering path — collaborators just won't have that local file.
  domainFileList = lib.concatStringsSep "\n        " (lib.mapAttrsToList
    (dom: files: ''
      if [ "$d" = ${lib.escapeShellArg dom} ]; then
        ${lib.concatMapStringsSep "\n        " (f: ''printf '%s\n' ${lib.escapeShellArg f}'') files}
      fi'')
    domainSteering);

  projectSteeringHelper = pkgs.writeShellApplication {
    name = "project-steering";
    runtimeInputs = [ pkgs.coreutils pkgs.gnugrep ];
    text = ''
      steering_dir="$HOME/.claude/steering"   # global steering files live here (all agents share)
      avail=${lib.escapeShellArg (lib.concatStringsSep " " (lib.attrNames domainSteering))}
      if [ "$#" -eq 0 ]; then
        echo "usage: project-steering <domain>...   (available: $avail)" >&2
        echo "layers domain steering into CLAUDE.md (Claude/Pi), AGENTS.md" >&2
        echo "(Codex/Maki/Pi) and .kiro/steering (Kiro) — non-destructive." >&2
        exit 0
      fi
      # Validate domains + collect the per-domain steering file names.
      files=""
      for d in "$@"; do
        case " $avail " in
          *" $d "*) ;;
          *) echo "project-steering: unknown domain '$d' (have: $avail)" >&2; continue ;;
        esac
        for f in $(
          ${domainFileList}
        ); do files="$files $f"; done
      done

      # --- Claude + Pi: ./.claude/steering-domains.md  (@import absolute) ---
      mkdir -p .claude
      {
        echo "# Project domain steering (domains: $*)"
        echo "# Generated by project-steering; @imported from .claude/CLAUDE.md."
        echo
        for f in $files; do echo "@$steering_dir/$f"; done
      } > .claude/steering-domains.md
      claude_import="@steering-domains.md"
      if [ ! -f .claude/CLAUDE.md ]; then
        printf '# Project instructions\n\n%s\n' "$claude_import" > .claude/CLAUDE.md
      elif ! grep -qxF "$claude_import" .claude/CLAUDE.md; then
        printf '\n%s\n' "$claude_import" >> .claude/CLAUDE.md
      fi

      # --- Codex + Maki + Pi: ./AGENTS.md references ./.agent-steering-domains.md ---
      # AGENTS.md may be committed/shared, so include a RELATIVE local file
      # (gitignored) rather than absolute host paths. Inline the domain
      # content so collaborators missing the file just lack the extra steer.
      {
        echo "# Project domain steering (domains: $*)"
        echo "# Generated by project-steering (local, gitignored)."
        echo
        for f in $files; do
          echo "## $f"
          ${pkgs.coreutils}/bin/cat "$steering_dir/$f" 2>/dev/null || true
          echo
        done
      } > .agent-steering-domains.md
      agents_ref="See .agent-steering-domains.md for domain-specific steering (local)."
      if [ ! -f AGENTS.md ]; then
        printf '# Project instructions\n\n%s\n' "$agents_ref" > AGENTS.md
      elif ! grep -qF ".agent-steering-domains.md" AGENTS.md; then
        printf '\n%s\n' "$agents_ref" >> AGENTS.md
      fi

      # --- Kiro: drop the domain files into ./.kiro/steering/ ---
      mkdir -p .kiro/steering
      for f in $files; do
        ${pkgs.coreutils}/bin/ln -sf "$steering_dir/$f" ".kiro/steering/domain-$f"
      done

      echo "project-steering: layered [$*] into CLAUDE.md, AGENTS.md, .kiro/steering" >&2
    '';
  };
in
{
  options.programs.ai.steering = {
    enable = mkEnableOption "Deploy shared steering/instruction files for AI agents";

    targets = {
      kiro = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy to ~/.kiro/steering/";
      };
      claude = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy full steering to ~/.claude/CLAUDE.md";
      };
      pi = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy all steering files to ~/.pi/agent/prompts/";
      };
      maki = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy consolidated instructions to ~/.config/maki/instructions.md";
      };
      codex = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy consolidated instructions to ~/.codex/instructions.md";
      };
    };

    extraFiles = mkOption {
      type = types.attrsOf types.path;
      default = { };
      description = "Additional steering files to deploy (name -> path)";
    };
  };

  config = lib.mkIf cfg.enable {
    # claude-steering helper for per-project domain opt-in (used from .envrc).
    # project-steering: cross-agent per-project domain scoping (used from
    # .envrc). Gated on the claude target since the global steering files it
    # sources live under ~/.claude/steering/.
    home.packages = lib.optional cfg.targets.claude projectSteeringHelper;

    home.file = lib.mkMerge [
      # Kiro steering files (individual files in ~/.kiro/steering/)
      (lib.mkIf cfg.targets.kiro (
        lib.mapAttrs'
          (name: path: lib.nameValuePair ".kiro/steering/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles)
      ))

      # Claude global CLAUDE.md — a small index that @imports the
      # individual steering files from ~/.claude/steering/. Inlining all
      # nine files produced a 40.5k-char CLAUDE.md, tripping Claude
      # Code's "Large CLAUDE.md will impact performance (>40k chars)"
      # warning (the check measures the top-level file on disk). Claude
      # resolves @imports recursively, so it still sees every rule while
      # the index file itself stays tiny.
      (lib.mkIf cfg.targets.claude (lib.mkMerge [
        (lib.mapAttrs'
          (name: path: lib.nameValuePair ".claude/steering/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles))
        {
          ".claude/CLAUDE.md".text = ''
            # Steering

            These standards apply equally in Claude Code, Kiro CLI, Pi, Maki,
            and Codex. The detailed rules live in ~/.claude/steering/ and are
            imported below; read AGENTS.md for project-specific instructions.

            Domain-specific steering (PostgreSQL, AWS, Rust) is NOT imported
            globally — it's opt-in per project. In a project's .envrc run
            `eval "$(project-steering postgresql)"` (or `aws`, `rust`) to add
            it via a project-local .claude/CLAUDE.md.

          '' + builtins.concatStringsSep "\n"
            (map (name: "@~/.claude/steering/${name}") universalSteering)
          + "\n";
        }
      ]))

      # Pi prompts — all steering files as individual prompts
      (lib.mkIf cfg.targets.pi (
        lib.mapAttrs'
          (name: path: lib.nameValuePair ".pi/agent/prompts/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles)
      ))

      # Maki global instructions (all steering concatenated)
      (lib.mkIf cfg.targets.maki {
        ".config/maki/instructions.md".text = allSteeringContent;
      })

      # Codex instructions (all steering concatenated)
      (lib.mkIf cfg.targets.codex {
        ".codex/instructions.md".text = allSteeringContent;
      })
    ];
  };
}
