{ config, lib, pkgs, ... }:
let
  cfg = config.programs.ai.steering;
  inherit (lib) mkEnableOption mkOption types;

  steeringFiles = {
    "must-rules.md" = ./files/steering/must-rules.md;
    "coding-standards.md" = ./files/steering/coding-standards.md;
    "rust-conventions.md" = ./files/steering/rust-conventions.md;
    "workflow.md" = ./files/steering/workflow.md;
    "tools.md" = ./files/steering/tools.md;
    "aws-builder.md" = ./files/steering/aws-builder.md;
    "mcp-config.md" = ./files/steering/mcp-config.md;
    "postgresql-workflow.md" = ./files/steering/postgresql-workflow.md;
    "voice.md" = ./files/steering/voice.md;
  };

  # Per-project context scoping. The GLOBAL Claude CLAUDE.md should only
  # @import the UNIVERSAL rules (always relevant); DOMAIN files (e.g. the
  # 15k-char postgresql-workflow) are opt-in per project so they don't burn
  # context in unrelated repos (e.g. an OS-kernel project pulling in
  # Postgres steering). Domain files are still deployed to
  # ~/.claude/steering/ so a project CLAUDE.md can @import them on demand;
  # the `claude-steering` helper (for .envrc) writes that project file.
  universalSteering = [
    "must-rules.md" "coding-standards.md" "workflow.md"
    "tools.md" "voice.md" "mcp-config.md"
  ];
  domainSteering = {
    postgresql = [ "postgresql-workflow.md" ];
    aws = [ "aws-builder.md" ];
    rust = [ "rust-conventions.md" ];
  };

  # Concatenated steering for agents that use a single instructions file
  allSteeringContent = builtins.concatStringsSep "\n\n"
    (map builtins.readFile (builtins.attrValues steeringFiles));

  # direnv helper: in a project's .envrc, run e.g.
  #   eval "$(claude-steering postgresql aws)"   (or: use claude_steering postgresql)
  # to add the chosen domain bundles ON TOP of the global universal set.
  # With no args it lists domains.
  #
  # NON-DESTRUCTIVE: writes the @import list to ./.claude/steering-domains.md
  # and ensures ./.claude/CLAUDE.md @imports it WITHOUT clobbering any
  # hand-written project CLAUDE.md (it appends the one import line if absent,
  # else creates a minimal CLAUDE.md). Recommend gitignoring
  # .claude/steering-domains.md (it's local context, host-path-specific).
  claudeSteeringHelper = pkgs.writeShellApplication {
    name = "claude-steering";
    runtimeInputs = [ pkgs.coreutils pkgs.gnugrep ];
    text = ''
      domains_dir="$HOME/.claude/steering"
      avail=${lib.escapeShellArg (lib.concatStringsSep " " (lib.attrNames domainSteering))}
      if [ "$#" -eq 0 ]; then
        echo "usage: claude-steering <domain>...   (available: $avail)" >&2
        echo "adds domain steering to ./.claude via steering-domains.md (non-destructive)" >&2
        exit 0
      fi
      mkdir -p .claude
      dom_file=.claude/steering-domains.md
      {
        echo "# Project domain steering (domains: $*)"
        echo "# Generated by claude-steering; @imported from .claude/CLAUDE.md."
        echo
        for d in "$@"; do
          case " $avail " in
            *" $d "*) ;;
            *) echo "claude-steering: unknown domain '$d' (have: $avail)" >&2; continue ;;
          esac
          ${lib.concatStringsSep "\n        " (lib.mapAttrsToList (dom: files: ''
            if [ "$d" = ${lib.escapeShellArg dom} ]; then
              ${lib.concatMapStringsSep "\n              " (f: ''echo "@$domains_dir/${f}"'') files}
            fi'') domainSteering)}
        done
      } > "$dom_file"
      # Ensure .claude/CLAUDE.md @imports the domain file, preserving any
      # existing hand-written content.
      import_line="@steering-domains.md"
      if [ ! -f .claude/CLAUDE.md ]; then
        printf '# Project instructions\n\n%s\n' "$import_line" > .claude/CLAUDE.md
      elif ! grep -qxF "$import_line" .claude/CLAUDE.md; then
        printf '\n%s\n' "$import_line" >> .claude/CLAUDE.md
      fi
      echo "claude-steering: $dom_file (domains: $*); CLAUDE.md imports it" >&2
    '';
  };
in
{
  options.programs.ai.steering = {
    enable = mkEnableOption "Deploy shared steering/instruction files for AI agents";

    targets = {
      kiro = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy to ~/.kiro/steering/";
      };
      claude = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy full steering to ~/.claude/CLAUDE.md";
      };
      pi = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy all steering files to ~/.pi/agent/prompts/";
      };
      maki = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy consolidated instructions to ~/.config/maki/instructions.md";
      };
      codex = mkOption {
        type = types.bool;
        default = true;
        description = "Deploy consolidated instructions to ~/.codex/instructions.md";
      };
    };

    extraFiles = mkOption {
      type = types.attrsOf types.path;
      default = { };
      description = "Additional steering files to deploy (name -> path)";
    };
  };

  config = lib.mkIf cfg.enable {
    # claude-steering helper for per-project domain opt-in (used from .envrc).
    home.packages = lib.optional cfg.targets.claude claudeSteeringHelper;

    home.file = lib.mkMerge [
      # Kiro steering files (individual files in ~/.kiro/steering/)
      (lib.mkIf cfg.targets.kiro (
        lib.mapAttrs'
          (name: path: lib.nameValuePair ".kiro/steering/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles)
      ))

      # Claude global CLAUDE.md — a small index that @imports the
      # individual steering files from ~/.claude/steering/. Inlining all
      # nine files produced a 40.5k-char CLAUDE.md, tripping Claude
      # Code's "Large CLAUDE.md will impact performance (>40k chars)"
      # warning (the check measures the top-level file on disk). Claude
      # resolves @imports recursively, so it still sees every rule while
      # the index file itself stays tiny.
      (lib.mkIf cfg.targets.claude (lib.mkMerge [
        (lib.mapAttrs'
          (name: path: lib.nameValuePair ".claude/steering/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles))
        {
          ".claude/CLAUDE.md".text = ''
            # Steering

            These standards apply equally in Claude Code, Kiro CLI, Pi, Maki,
            and Codex. The detailed rules live in ~/.claude/steering/ and are
            imported below; read AGENTS.md for project-specific instructions.

            Domain-specific steering (PostgreSQL, AWS, Rust) is NOT imported
            globally — it's opt-in per project. In a project's .envrc run
            `eval "$(claude-steering postgresql)"` (or `aws`, `rust`) to add
            it via a project-local .claude/CLAUDE.md.

          '' + builtins.concatStringsSep "\n"
            (map (name: "@~/.claude/steering/${name}") universalSteering)
          + "\n";
        }
      ]))

      # Pi prompts — all steering files as individual prompts
      (lib.mkIf cfg.targets.pi (
        lib.mapAttrs'
          (name: path: lib.nameValuePair ".pi/agent/prompts/${name}" { source = path; })
          (steeringFiles // cfg.extraFiles)
      ))

      # Maki global instructions (all steering concatenated)
      (lib.mkIf cfg.targets.maki {
        ".config/maki/instructions.md".text = allSteeringContent;
      })

      # Codex instructions (all steering concatenated)
      (lib.mkIf cfg.targets.codex {
        ".codex/instructions.md".text = allSteeringContent;
      })
    ];
  };
}
