name: Flake ❄️ Lock 🔒️ Updater ✨

on:
  schedule:
    # Pi o'clock
    - cron: '3 14 * * 1,5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a  # v21
      - uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39  # v13
      - uses: DeterminateSystems/update-flake-lock@834c491b2ece4de0bbd00d85214bb5e83b4da5c6  # v28
        with:
          pr-title: "chore: update flake.lock"
          # Labels to be set on the PR
          pr-labels: |
            dependencies
            automated
